[package]
name = "all-battle-core"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
serde = "1.0.204"
serde_derive = "1.0.204"
serde_json = "1.0.120"
diesel = { version = "2.2.1", features = ["returning_clauses_for_sqlite_3_35", "sqlite"] }
log = "0.4.22"
